<script setup lang="ts">
import { useTopics } from '~/composables/useTopics'
import { useLessons } from '~/composables/useLessons'
import { computed, onMounted } from 'vue'
import { injectAssessmentsIntoTimeline } from '~/utils/seeder'

const route = useRoute()
const { topics } = useTopics()
const { getLessonsByTopic, addAssessments, addLessonContents, updateLessonsForTopic } = useLessons()

const topic = computed(() => {
    return topics.value.find(t => t.id === route.params.id)
})

const { data: serverLessons } = await useFetch(`/api/lessons?topicId=${route.params.id}`)

const lessons = computed(() => {
    const local = getLessonsByTopic(route.params.id as string)
    return local.length > 0 ? local : (serverLessons.value || [])
})

const injectAssessments = () => {
    if (!topic.value) return
    const currentLessons = [...lessons.value]
    if (currentLessons.length === 0) return
    
    // Check if we already have assessments (to avoid infinite loop or duplication)
    const hasQuizzes = currentLessons.some(l => l.type === 'quiz')
    if (hasQuizzes) return

    // Use centralized logic to inject assessments
    const { 
        newTimeline, 
        newAssessments, 
        newContents 
    } = injectAssessmentsIntoTimeline(route.params.id as string, topic.value.title, currentLessons as any[])

    updateLessonsForTopic(route.params.id as string, newTimeline)
    addLessonContents(newContents)
    addAssessments(newAssessments)
}

onMounted(() => {
    injectAssessments()
})

useHead({
    title: topic.value ? `${topic.value.title} - LearnFast` : 'Topic Not Found'
})
</script>

<template>
    <UContainer v-if="topic" class="flex flex-col gap-6 py-6">
        <div class="flex flex-col gap-8 pb-12">
            <!-- Hero Section -->
            <UCard class="relative overflow-hidden" :ui="{ body: 'p-8 sm:p-10' }">
                <div
                    class="absolute inset-0 bg-gradient-to-br from-primary-500/10 via-transparent to-transparent pointer-events-none" />

                <div class="relative z-10 flex flex-col md:flex-row md:items-center justify-between gap-6">
                    <div class="flex items-start gap-4 w-full">
                        <div class="bg-primary/10 p-4 rounded-2xl shrink-0">
                            <UIcon :name="topic.icon" class="text-4xl text-primary flex shrink-0" />
                        </div>
                        <div class="flex-1">
                            <h1 class="text-2xl sm:text-3xl font-bold tracking-tight">{{ topic.title }}</h1>
                            <p class="text-dimmed mt-1 max-w-lg">
                                Master this topic with an AI-curated learning path tailored to your specific materials
                                and objectives.
                            </p>
                        </div>
                        <div class="flex items-center gap-2">
                            <UBadge :label="topic.tag" variant="soft" />
                            <UBadge v-if="topic.learningGoal" :label="topic.learningGoal" variant="subtle"
                                color="primary" />
                        </div>
                    </div>
                </div>
            </UCard>

            <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
                <!-- Main Timeline Column -->
                <div class="md:col-span-2 flex flex-col gap-6">

                    <div class="flex items-center justify-between border-b border-default pb-4">
                        <h2 class="text-lg font-bold flex items-center gap-2">
                            <UIcon name="i-lucide-list-ordered" class="text-primary" />
                            Lesson Timeline
                        </h2>
                        <UBadge label="Generated by AI" variant="soft" color="neutral" size="sm"
                            class="text-dimmed uppercase tracking-wider text-xs font-medium px-2 py-1 rounded-md" />
                    </div>

                    <!-- TIMELINE COMPONENT -->
                    <div class="relative pl-6 ml-2 mt-4 space-y-8">
                        <!-- Vertical Line -->
                        <div
                            class="absolute left-[-1px] top-0 bottom-0 w-0.5 h-full bg-neutral-200 dark:bg-neutral-800 rounded-full" />

                        <div v-for="(lesson, index) in lessons" :key="index" class="relative group">
                            <!-- Timeline Dot / Icon -->
                            <div class="absolute -left-[37px] w-7 h-7 rounded-full flex items-center justify-center border-[3px] border-white dark:border-neutral-900 z-10 transition-colors duration-300"
                                :class="{
                                    'bg-green-500 text-white': lesson.status === 'completed',
                                    'shadow-[0_0_15px_rgba(var(--color-primary-500),0.5)]': lesson.status === 'current',
                                    'bg-primary-500 text-white': lesson.status === 'current' && lesson.color === 'primary',
                                    'bg-orange-500 text-white': lesson.status === 'current' && lesson.color === 'orange',
                                    'bg-purple-500 text-white': lesson.status === 'current' && lesson.color === 'purple',
                                    'bg-neutral-200 dark:bg-neutral-800 text-dimmed': lesson.status === 'locked'
                                }">
                                <UIcon v-if="lesson.status === 'completed'" name="i-lucide-check" class="text-sm" />
                                <div v-else-if="lesson.status === 'current'"
                                    class="w-2 h-2 rounded-full bg-white animate-ping" />
                                <div v-else class="w-1.5 h-1.5 rounded-full bg-neutral-400 dark:bg-neutral-600" />
                            </div>

                            <!-- Content Card -->
                            <UCard variant="subtle" class="transition-all duration-300 transform" :class="{
                                'opacity-70 grayscale-[0.3] hover:grayscale-0 hover:opacity-100 cursor-pointer'
                                    : lesson.status === 'completed',
                                'ring-2 shadow-md transform -translate-y-1 relative overflow-hidden'
                                    : lesson.status === 'current',
                                'ring-primary-500': lesson.status === 'current' && lesson.color === 'primary',
                                'ring-orange-500': lesson.status === 'current' && lesson.color === 'orange',
                                'ring-purple-500': lesson.status === 'current' && lesson.color === 'purple',
                                'opacity-50 pointer-events-none'
                                    : lesson.status === 'locked',
                                'hover:-translate-y-1 hover:shadow-md cursor-pointer'
                                    : lesson.status !== 'locked' && lesson.status !== 'current'
                            }" :ui="{ body: 'flex items-start gap-4 p-4 sm:p-5' }">
                                <template v-if="lesson.status === 'current'">
                                    <div v-if="lesson.color === 'primary'" class="absolute inset-0 bg-primary-500/5 pointer-events-none" />
                                    <div v-if="lesson.color === 'orange'" class="absolute inset-0 bg-orange-500/5 pointer-events-none" />
                                    <div v-if="lesson.color === 'purple'" class="absolute inset-0 bg-purple-500/5 pointer-events-none" />
                                </template>
                                <div class="bg-neutral-100 dark:bg-neutral-800 p-2.5 rounded-lg shrink-0"
                                    :class="{ 
                                        'text-primary-500 dark:text-primary-400 bg-primary-100 dark:bg-primary-500/10': lesson.status === 'current' && lesson.color === 'primary',
                                        'text-orange-500 dark:text-orange-400 bg-orange-100 dark:bg-orange-500/10': lesson.status === 'current' && lesson.color === 'orange',
                                        'text-purple-500 dark:text-purple-400 bg-purple-100 dark:bg-purple-500/10': lesson.status === 'current' && lesson.color === 'purple'
                                    }">
                                    <UIcon :name="lesson.icon" class="text-lg flex" />
                                </div>
                                <div class="flex-1 min-w-0">
                                    <div class="flex items-center justify-between gap-2">
                                        <h3 class="font-bold text-base truncate"
                                            :class="{ 
                                                'text-primary-600 dark:text-primary-400': lesson.status === 'current' && lesson.color === 'primary',
                                                'text-orange-600 dark:text-orange-400': lesson.status === 'current' && lesson.color === 'orange',
                                                'text-purple-600 dark:text-purple-400': lesson.status === 'current' && lesson.color === 'purple'
                                            }">
                                            {{ lesson.title }}
                                        </h3>
                                        <UBadge variant="subtle" size="sm"
                                            :color="lesson.status === 'current' ? 'primary' : 'neutral'"
                                            class="shrink-0 font-medium font-mono">
                                            {{ lesson.duration }}
                                        </UBadge>
                                    </div>
                                    <p class="text-sm text-dimmed mt-1.5 leading-relaxed truncate">{{ lesson.summary
                                    }}
                                    </p>
                                    <div class="flex items-center gap-3 mt-4" v-if="lesson.status !== 'locked'">
                                        <UButton v-if="lesson.status === 'current'" 
                                            :label="lesson.type === 'quiz' ? 'Start Review' : 'Start Lesson'"
                                            icon="i-lucide-play-circle" color="primary" size="sm"
                                            :to="`/app/lesson/${lesson.id}`" />
                                        <UButton v-else 
                                            :label="lesson.type === 'quiz' ? 'Review Milestone' : 'Review'" 
                                            icon="i-lucide-rotate-ccw" color="neutral"
                                            variant="soft" size="sm"
                                            :to="`/app/lesson/${lesson.id}`" />
                                    </div>
                                </div>
                            </UCard>
                        </div>
                    </div>
                </div>

                <!-- Sidebar Content -->
                <div class="flex flex-col gap-6">
                    <!-- Progress Card -->
                    <UCard variant="soft" :ui="{ body: 'p-5 flex flex-col gap-4' }">
                        <div>
                            <div class="flex items-center justify-between mb-2">
                                <span class="text-sm font-semibold uppercase tracking-wider text-muted">
                                    Overall Progress
                                </span>
                                <span class="text-sm font-bold text-primary">{{ topic.progress }}%</span>
                            </div>
                            <UProgress :model-value="topic.progress" color="primary" size="sm" />
                        </div>
                        <p class="text-xs text-dimmed">
                            You are doing great! Keep up the momentum to reach your goal.
                        </p>
                    </UCard>

                    <!-- Knowledge Sources Details -->
                    <UCard variant="soft" :ui="{ body: 'p-5 flex flex-col gap-3' }"
                        class="bg-blue-50/50 dark:bg-blue-900/10">
                        <div class="flex items-center gap-2 mb-1">
                            <UIcon name="i-lucide-brain-circuit" class="text-blue-500" />
                            <h3 class="text-sm font-semibold uppercase tracking-wider text-blue-500">AI Context</h3>
                        </div>
                        <p class="text-xs text-dimmed mb-2">
                            This syllabus was dynamically generated from your uploaded materials.
                        </p>

                        <div class="flex flex-col gap-2">
                            <UCard :ui="{ body: 'flex items-center gap-2 p-2 sm:p-2' }" class="rounded-md shadow-sm">
                                <UIcon name="i-lucide-file-text" class="text-red-500 shrink-0" />
                                <span class="text-xs font-medium truncate">{{ topic.title }} Chapter 1-3.pdf</span>
                            </UCard>
                            <UCard :ui="{ body: 'flex items-center gap-2 p-2 sm:p-2' }" class="rounded-md shadow-sm">
                                <UIcon name="i-lucide-presentation" class="text-orange-500 shrink-0" />
                                <span class="text-xs font-medium truncate">Lecture_Deck_Final.pptx</span>
                            </UCard>
                        </div>
                    </UCard>
                </div>

            </div>
        </div>
    </UContainer>

    <!-- 404 Empty State -->
    <div v-else class="flex flex-col items-center justify-center py-20 text-center">
        <UIcon name="i-lucide-file-search-corner" class="text-6xl text-dimmed mb-4" />
        <h2 class="text-2xl font-bold">Topic not found</h2>
        <p class="text-muted mt-2">The topic you're looking for doesn't exist or has been deleted.</p>
        <UButton label="Back to Dashboard" color="primary" variant="subtle" to="/app/dashboard" class="mt-6" />
    </div>
</template>
